spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000  # 5 minutes
      connection-timeout: 20000  # 20 seconds
      max-lifetime: 1200000  # 20 minutes
      pool-name: HikariPool-Stathis
      validation-timeout: 5000
      leak-detection-threshold: 60000
      register-mbeans: true

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
          fetch_size: 25
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: false
    hibernate:
      ddl-auto: update

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 